//
// Copyright 2019 Dynatrace LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

namespace Dynatrace.OneAgent.Sdk.Api
{
    /// <summary>
    /// Common interface to allow outgoing requests to be linked to incoming requests via tags.
    /// Not to be referenced directly by SDK users.
    /// </summary>
    public interface IOutgoingTaggable
    {
        /// <summary>
        /// Creates a Dynatrace tag for an outgoing request and returns the string representation of it.
        /// A tag can only be retrieved after the tracer was started (see <see cref="ITracer.Start"/> and others).
        /// 
        /// To allow tracing across process and technology boundaries, tracers can be supplied with so-called tags.
        /// Tags are strings or byte arrays generated by the SDK that enable Dynatrace to trace a transaction end-to-end.
        /// The user has to take care of transporting the tag from one process/service to the other.
        /// 
        /// See <see cref="IIncomingTaggable"/> on how to continue a path with the tag provided here on the receiving side.
        /// </summary>
        /// <returns>the tag to be used with <see cref="IIncomingTaggable.SetDynatraceStringTag(string)"/>, never null</returns>
        string GetDynatraceStringTag();

        /// <summary>
        /// Same as <see cref="GetDynatraceStringTag"/> but returning the tag as binary representation.
        /// A tag can only be retrieved after the tracer was started (see <see cref="ITracer.Start"/> and others).
        /// </summary>
        /// <returns>the tag to be used with <see cref="IIncomingTaggable.SetDynatraceByteTag(byte[])"/>, never null</returns>
        byte[] GetDynatraceByteTag();
    }
}
